name: "React-ci-cd-pipeline/workflow"

on:
  push:
    branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: "Set up Node.js"
          uses: actions/setup-node@v4
          with:
            node-version: "20"
        
        - name: "check node version"
          run: node --version
        
        - name: "clone repository"
          uses: actions/checkout@v3

        - name: "install dependencies"
          run: npm install

        - name: "list directory"
          run: ls 
        
        - name: :"run lint"
          run: npm run lint
          
        - name: "build application"
          run: npm run build 
        
        - name: "upload artifact"
          uses: actions/upload-artifact@v3
          with:
            name: build
            path: dist